services:
    Github\Client:
        class: LMMS\GithubDownloadClient
        arguments:
            - '@Github\HttpClient\Builder'
        calls:
           - ['authenticate', ['%env(GITHUB_USERNAME)%', '%env(GITHUB_SECRET)%', '%env(GITHUB_AUTH_METHOD)%']]
           - ['addCache', ['@github_api.cache', {default_ttl: 1800}]]

    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Http\Message\RequestFactory'
            - '@?Http\Message\StreamFactory'
